export const class3: CTClass = {
  name: "Rowan",
  pupils: [
    {
      id: 1,
      first_name: "Frank",
      last_name: "Ervine",
      year: 4,
      CTclass: "Rowan",
    },
    {
      id: 2,
      first_name: "Hilde",
      last_name: "Monkman",
      year: 4,
      CTclass: "Rowan",
    },
    {
      id: 3,
      first_name: "Franzen",
      last_name: "Goldstein",
      year: 4,
      CTclass: "Rowan",
    },
    {
      id: 4,
      first_name: "Joella",
      last_name: "Slainey",
      year: 4,
      CTclass: "Rowan",
    },
    {
      id: 4,
      first_name: "Kaye",
      last_name: "Aslie",
      year: 4,
      CTclass: "Rowan",
    },
    {
      id: 6,
      first_name: "Caressa",
      last_name: "Shurmore",
      year: 4,
      CTclass: "Rowan",
    },
    {
      id: 7,
      first_name: "Isak",
      last_name: "Matiebe",
      year: 4,
      CTclass: "Rowan",
    },
    {
      id: 8,
      first_name: "Blaire",
      last_name: "Swiers",
      year: 4,
      CTclass: "Rowan",
    },
    {
      id: 9,
      first_name: "Meier",
      last_name: "Eskell",
      year: 4,
      CTclass: "Rowan",
    },
    {
      id: 10,
      first_name: "Trey",
      last_name: "Aloway",
      year: 4,
      CTclass: "Rowan",
    },
    {
      id: 11,
      first_name: "Chaddy",
      last_name: "Kelemen",
      year: 4,
      CTclass: "Rowan",
    },
    {
      id: 12,
      first_name: "Kate",
      last_name: "Czyz",
      year: 4,
      CTclass: "Rowan",
    },
    {
      id: 13,
      first_name: "Artemus",
      last_name: "Cleghorn",
      year: 4,
      CTclass: "Rowan",
    },
    {
      id: 14,
      first_name: "Joela",
      last_name: "Dunan",
      year: 4,
      CTclass: "Rowan",
    },
    {
      id: 15,
      first_name: "Kerrie",
      last_name: "Aupol",
      year: 4,
      CTclass: "Rowan",
    },
    {
      id: 16,
      first_name: "Bonnie",
      last_name: "Colleer",
      year: 4,
      CTclass: "Rowan",
    },
    {
      id: 17,
      first_name: "Marcia",
      last_name: "O'Sharkey",
      year: 4,
      CTclass: "Rowan",
    },
    {
      id: 18,
      first_name: "Belle",
      last_name: "Pundy",
      year: 4,
      CTclass: "Rowan",
    },
    {
      id: 19,
      first_name: "Gus",
      last_name: "Charon",
      year: 4,
      CTclass: "Rowan",
    },
    {
      id: 20,
      first_name: "Lillis",
      last_name: "Lunnon",
      year: 4,
      CTclass: "Rowan",
    },
    {
      id: 21,
      first_name: "Baxy",
      last_name: "Wyse",
      year: 4,
      CTclass: "Rowan",
    },
    {
      id: 22,
      first_name: "Maxwell",
      last_name: "Chapelhow",
      year: 4,
      CTclass: "Rowan",
    },
    {
      id: 23,
      first_name: "Cammy",
      last_name: "Handy",
      year: 4,
      CTclass: "Rowan",
    },
    {
      id: 24,
      first_name: "Lauren",
      last_name: "Chrestien",
      year: 4,
      CTclass: "Rowan",
    },
    {
      id: 25,
      first_name: "Cherin",
      last_name: "Northway",
      year: 4,
      CTclass: "Rowan",
    },
    {
      id: 26,
      first_name: "Cobb",
      last_name: "Humberston",
      year: 4,
      CTclass: "Rowan",
    },
    {
      id: 27,
      first_name: "Gino",
      last_name: "Balaizot",
      year: 4,
      CTclass: "Rowan",
    },
    {
      id: 28,
      first_name: "Penelope",
      last_name: "Ochterlony",
      year: 4,
      CTclass: "Rowan",
    },
    {
      id: 29,
      first_name: "Perry",
      last_name: "Ibarra",
      year: 4,
      CTclass: "Rowan",
    },
    {
      id: 30,
      first_name: "Waiter",
      last_name: "Angric",
      year: 4,
      CTclass: "Rowan",
    },
    {
      id: 31,
      first_name: "Adela",
      last_name: "Audrey",
      year: 4,
      CTclass: "Rowan",
    },
    {
      id: 32,
      first_name: "Giraldo",
      last_name: "Ors",
      year: 4,
      CTclass: "Rowan",
    },
  ],
};
